# Configuración de patrocinio para GitHub
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom: ['https://paypal.me/TU_USUARIO_PAYPAL']
